# Không checkout để tránh lỗi, xử lý clone repo mới
# remote unpack failed: error Shallow object update failed: The object 2e5aa7d6f92bafdc75089d7a30287e1d082c7ddf is being referenced but does not exist.
trigger:
  branches:
    include:
      - refs/heads/main
jobs:
  - job: pushtoothers
    displayName: pushtoothers
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UseNode@1
        displayName: Install NodeJS 18.x
        inputs:
          version: "18.x"

      - task: Bash@3
        displayName: Clone and decrypt dist
        env:
          SYTEM_ACCESS_TOKEN: $(System.AccessToken)
        inputs:
          targetType: inline
          script: |
            git clone https://o-adv@dev.azure.com/o-adv/o-svr-repo-aes-yml/_git/o-svr-repo-aes-yml ./dist
            if [ -f "./dist/oAESFile.js" ]; then node ./dist/oAESFile.js --de $(oAESFile) ./dist; fi

      - task: Bash@3
        displayName: Run ./.azure/push.aessecret.sh
        env:
          SYTEM_ACCESS_TOKEN: $(System.AccessToken)
        inputs:
          targetType: "inline"
          workingDirectory: ./dist
          script: |
            chmod u=rwx ./.azure/push.aessecret.sh
            ./.azure/push.aessecret.sh
